using System;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace Macedon.CharacterVisualVariants.Editor
{
    public sealed class CharacterVisualVariantsWindow : EditorWindow
    {
        private const string MenuPath = "Tools/MACEDON/Character Visual Variants";
        private const string SupportedMaterialGuid = "295e1776c89991848aea2de304fa38ad";
        private const string GeneratedRoot = "Assets/Generated/CharacterVisualVariants";
        private const string MetadataPrefix = "MACEDON_VARIANT_BASE_GUID=";

        private GameObject selectedCharacter;
        private SkinnedMeshRenderer eligibleRenderer;
        private Material baseMaterial;
        private Material previewMaterial;
        private Texture2D previewTexture;
        private Material materialBeforePreview;
        private int seed = 1;
        private int fabricPaletteIndex;
        private int shieldPaletteIndex;
        private string status;

        [MenuItem(MenuPath, false, 140)]
        private static void Open() => GetWindow<CharacterVisualVariantsWindow>("Character Variants");

        private void OnEnable()
        {
            Selection.selectionChanged += SelectionChanged;
            SelectionChanged();
        }

        private void OnDisable()
        {
            Selection.selectionChanged -= SelectionChanged;
            ClearPreview();
        }

        private void SelectionChanged()
        {
            ClearPreview();
            selectedCharacter = Selection.activeGameObject;
            DetectEligibleRenderer();
            status = null;
            Repaint();
        }

        private void OnGUI()
        {
            EditorGUILayout.HelpBox(
                "Editor-only, Varangian-specific prototype tool. Independent color-threshold masks recolor red fabric and blue paint on the known round-shield UV island. Other atlas regions are not globally tinted.",
                MessageType.Info);

            using (new EditorGUI.DisabledScope(true))
            {
                EditorGUILayout.ObjectField("Selected Character", selectedCharacter, typeof(GameObject), true);
                EditorGUILayout.ObjectField("Eligible Renderer", eligibleRenderer, typeof(SkinnedMeshRenderer), true);
                EditorGUILayout.ObjectField("Source Material", baseMaterial, typeof(Material), false);
            }

            if (selectedCharacter == null)
            {
                EditorGUILayout.HelpBox("Select one character root (or its Varangian child) in the Hierarchy.", MessageType.Warning);
                return;
            }

            if (eligibleRenderer == null || baseMaterial == null)
            {
                EditorGUILayout.HelpBox(
                    "No supported Varangian renderer found. The selection must contain the Shieldbearer skinned mesh using Shieldbearer_MAT or a material generated by this tool.",
                    MessageType.Warning);
                return;
            }

            EditorGUILayout.Space();
            EditorGUILayout.LabelField("Deterministic Combination", EditorStyles.boldLabel);
            seed = EditorGUILayout.IntField("Seed", seed);
            if (GUILayout.Button("Randomize Both + Preview"))
            {
                fabricPaletteIndex = VarangianVisualVariantLogic.PaletteIndexForSeed(seed);
                shieldPaletteIndex = VarangianVisualVariantLogic.ShieldPaletteIndexForSeed(seed);
                CreatePreview();
            }

            EditorGUILayout.Space();
            EditorGUILayout.LabelField("Fabric Variation", EditorStyles.boldLabel);
            EditorGUI.BeginChangeCheck();
            fabricPaletteIndex = EditorGUILayout.Popup("Fabric Color", fabricPaletteIndex, PaletteNames(VarangianVisualVariantLogic.Palette));
            if (EditorGUI.EndChangeCheck()) CreatePreview();
            using (new EditorGUI.DisabledScope(true))
                EditorGUILayout.ColorField("Fabric Result", VarangianVisualVariantLogic.Palette[fabricPaletteIndex].Color);
            if (GUILayout.Button("Preview Selected Fabric Color")) CreatePreview();

            EditorGUILayout.Space();
            EditorGUILayout.LabelField("Shield Variation", EditorStyles.boldLabel);
            EditorGUI.BeginChangeCheck();
            shieldPaletteIndex = EditorGUILayout.Popup("Shield Color", shieldPaletteIndex, PaletteNames(VarangianVisualVariantLogic.ShieldPalette));
            if (EditorGUI.EndChangeCheck()) CreatePreview();
            using (new EditorGUI.DisabledScope(true))
                EditorGUILayout.ColorField("Shield Result", VarangianVisualVariantLogic.ShieldPalette[shieldPaletteIndex].Color);
            if (GUILayout.Button("Preview Selected Shield Color")) CreatePreview();

            using (new EditorGUILayout.HorizontalScope())
            {
                using (new EditorGUI.DisabledScope(previewMaterial == null))
                    if (GUILayout.Button("Apply Variation")) ApplyVariation();
                if (GUILayout.Button("Reset / Revert")) ResetMaterial();
            }

            if (!string.IsNullOrEmpty(status)) EditorGUILayout.HelpBox(status, MessageType.None);
            EditorGUILayout.HelpBox(
                "Apply creates a PNG and Material under Assets/Generated/CharacterVisualVariants, then assigns only that new material to this renderer with Undo. No source asset is edited.",
                MessageType.Info);
        }

        private static string[] PaletteNames(VarangianVisualVariantLogic.PaletteEntry[] palette)
        {
            var names = new string[palette.Length];
            for (int i = 0; i < names.Length; i++) names[i] = palette[i].Name;
            return names;
        }

        private void DetectEligibleRenderer()
        {
            eligibleRenderer = null;
            baseMaterial = null;
            if (selectedCharacter == null) return;

            Transform searchRoot = selectedCharacter.transform;
            SkinnedMeshRenderer[] renderers = searchRoot.GetComponentsInChildren<SkinnedMeshRenderer>(true);
            if (renderers.Length == 0 && searchRoot.parent != null)
                renderers = searchRoot.parent.GetComponentsInChildren<SkinnedMeshRenderer>(true);

            foreach (SkinnedMeshRenderer renderer in renderers)
            {
                Material candidate = renderer.sharedMaterial;
                Material original = GetOriginalMaterial(candidate);
                if (original != null && AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(original)) == SupportedMaterialGuid)
                {
                    eligibleRenderer = renderer;
                    baseMaterial = original;
                    return;
                }
            }
        }

        private static Material GetOriginalMaterial(Material material)
        {
            if (material == null) return null;
            string path = AssetDatabase.GetAssetPath(material);
            string guid = AssetDatabase.AssetPathToGUID(path);
            if (guid == SupportedMaterialGuid) return material;
            AssetImporter importer = AssetImporter.GetAtPath(path);
            if (importer == null || string.IsNullOrEmpty(importer.userData) ||
                !importer.userData.StartsWith(MetadataPrefix, StringComparison.Ordinal)) return null;
            string baseGuid = importer.userData.Substring(MetadataPrefix.Length);
            return AssetDatabase.LoadAssetAtPath<Material>(AssetDatabase.GUIDToAssetPath(baseGuid));
        }

        private void CreatePreview()
        {
            ClearPreview();
            if (!TryBuildTexture(out previewTexture, out int fabricChanged, out int shieldChanged)) return;
            previewTexture.name = "Varangian Variant Preview";
            previewTexture.hideFlags = HideFlags.HideAndDontSave;
            previewMaterial = new Material(baseMaterial)
            {
                name = "Varangian Variant Preview",
                hideFlags = HideFlags.HideAndDontSave,
                mainTexture = previewTexture
            };
            materialBeforePreview = eligibleRenderer.sharedMaterial;
            eligibleRenderer.sharedMaterial = previewMaterial;
            status = $"Previewing Fabric {VarangianVisualVariantLogic.Palette[fabricPaletteIndex].Name} + Shield {VarangianVisualVariantLogic.ShieldPalette[shieldPaletteIndex].Name}; {fabricChanged:N0} fabric and {shieldChanged:N0} shield pixels recolored.";
            SceneView.RepaintAll();
        }

        private bool TryBuildTexture(out Texture2D texture, out int fabricChanged, out int shieldChanged)
        {
            texture = null;
            fabricChanged = 0;
            shieldChanged = 0;
            Texture2D source = baseMaterial == null ? null : baseMaterial.mainTexture as Texture2D;
            string sourcePath = AssetDatabase.GetAssetPath(source);
            if (source == null || string.IsNullOrEmpty(sourcePath))
            {
                status = "The supported material has no readable project texture.";
                return false;
            }

            try
            {
                byte[] bytes = File.ReadAllBytes(Path.GetFullPath(sourcePath));
                texture = new Texture2D(2, 2, TextureFormat.RGBA32, true);
                if (!ImageConversion.LoadImage(texture, bytes, false)) throw new InvalidOperationException("Unity could not decode the source atlas.");
                Color32[] pixels = texture.GetPixels32();
                VarangianVisualVariantLogic.RecolorCombined(
                    pixels,
                    texture.width,
                    texture.height,
                    VarangianVisualVariantLogic.Palette[fabricPaletteIndex].Color,
                    VarangianVisualVariantLogic.ShieldPalette[shieldPaletteIndex].Color,
                    out fabricChanged,
                    out shieldChanged);
                texture.SetPixels32(pixels);
                texture.Apply(true, false);
                return true;
            }
            catch (Exception exception)
            {
                if (texture != null) DestroyImmediate(texture);
                texture = null;
                status = $"Could not create variant texture: {exception.Message}";
                return false;
            }
        }

        private void ApplyVariation()
        {
            if (previewTexture == null || previewMaterial == null || eligibleRenderer == null) return;
            EnsureFolder(GeneratedRoot);
            string safeName = SanitizeFileName(selectedCharacter.name);
            string fabricName = VarangianVisualVariantLogic.Palette[fabricPaletteIndex].Name.Replace(" ", string.Empty);
            string shieldName = VarangianVisualVariantLogic.ShieldPalette[shieldPaletteIndex].Name.Replace(" ", string.Empty);
            string stem = $"{safeName}_Seed{seed}_Fabric{fabricName}_Shield{shieldName}";
            string texturePath = AssetDatabase.GenerateUniqueAssetPath($"{GeneratedRoot}/{stem}.png");
            File.WriteAllBytes(Path.GetFullPath(texturePath), previewTexture.EncodeToPNG());
            AssetDatabase.ImportAsset(texturePath, ImportAssetOptions.ForceSynchronousImport);

            TextureImporter textureImporter = AssetImporter.GetAtPath(texturePath) as TextureImporter;
            if (textureImporter != null)
            {
                textureImporter.sRGBTexture = true;
                textureImporter.mipmapEnabled = true;
                textureImporter.alphaSource = TextureImporterAlphaSource.FromInput;
                textureImporter.SaveAndReimport();
            }

            Texture2D textureAsset = AssetDatabase.LoadAssetAtPath<Texture2D>(texturePath);
            var materialAsset = new Material(baseMaterial) { name = stem, mainTexture = textureAsset };
            string materialPath = AssetDatabase.GenerateUniqueAssetPath($"{GeneratedRoot}/{stem}.mat");
            AssetDatabase.CreateAsset(materialAsset, materialPath);
            AssetImporter materialImporter = AssetImporter.GetAtPath(materialPath);
            materialImporter.userData = MetadataPrefix + SupportedMaterialGuid;
            materialImporter.SaveAndReimport();

            Material previousMaterial = materialBeforePreview != null ? materialBeforePreview : baseMaterial;
            eligibleRenderer.sharedMaterial = previousMaterial;
            ClearPreview(false);
            Undo.RecordObject(eligibleRenderer, "Apply Character Visual Variation");
            eligibleRenderer.sharedMaterial = AssetDatabase.LoadAssetAtPath<Material>(materialPath);
            EditorUtility.SetDirty(eligibleRenderer);
            status = $"Applied {stem}. Created {texturePath} and {materialPath}.";
            SceneView.RepaintAll();
        }

        private void ResetMaterial()
        {
            if (eligibleRenderer == null || baseMaterial == null) return;
            ClearPreview();
            Undo.RecordObject(eligibleRenderer, "Reset Character Visual Variation");
            eligibleRenderer.sharedMaterial = baseMaterial;
            EditorUtility.SetDirty(eligibleRenderer);
            status = "Restored the original Shieldbearer material. Generated assets were retained for safe Undo/reference handling.";
            SceneView.RepaintAll();
        }

        private void ClearPreview(bool restoreRenderer = true)
        {
            if (restoreRenderer && eligibleRenderer != null && previewMaterial != null && eligibleRenderer.sharedMaterial == previewMaterial)
                eligibleRenderer.sharedMaterial = materialBeforePreview != null ? materialBeforePreview : baseMaterial;
            if (previewMaterial != null) DestroyImmediate(previewMaterial);
            if (previewTexture != null) DestroyImmediate(previewTexture);
            previewMaterial = null;
            previewTexture = null;
            materialBeforePreview = null;
        }

        private static void EnsureFolder(string path)
        {
            string[] parts = path.Split('/');
            string current = parts[0];
            for (int i = 1; i < parts.Length; i++)
            {
                string next = current + "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(next)) AssetDatabase.CreateFolder(current, parts[i]);
                current = next;
            }
        }

        private static string SanitizeFileName(string value)
        {
            foreach (char invalid in Path.GetInvalidFileNameChars()) value = value.Replace(invalid, '_');
            return string.IsNullOrWhiteSpace(value) ? "Varangian" : value;
        }
    }
}
